version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    command: >
      postgres -c timezone=America/Sao_Paulo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_dev
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
